const mongoose = require('mongoose');

/**
 * Task Schema — Smart Daily Planner
 * 
 * Each task represents a single study item generated by the smart planner.
 * Tasks are distributed: 70% syllabus (6 tasks) + 30% revision (2 tasks).
 */
const taskSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  title: {
    type: String,
    required: true,
  },
  subject: {
    type: String,
    required: true,
  },
  type: {
    type: String,
    enum: ['syllabus', 'revision'],
    required: true,
  },
  status: {
    type: String,
    enum: ['pending', 'completed'],
    default: 'pending',
  },
  scheduledDate: {
    type: String, // YYYY-MM-DD
    required: true,
  },
  sourceTopicId: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
  },
  priority: {
    type: String,
    enum: ['high', 'medium', 'low'],
    default: 'medium',
  },
  chapter: {
    type: String,
    default: '',
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

// Fast lookup: get all tasks for a user on a given day
taskSchema.index({ userId: 1, scheduledDate: 1 });

// Prevent duplicate tasks for the same topic on the same day
taskSchema.index({ userId: 1, scheduledDate: 1, sourceTopicId: 1 }, { unique: true });

module.exports = mongoose.model('Task', taskSchema);
